modLoader="javafml"
loaderVersion="*"
license="All rights reserved"
issueTrackerURL="https://github.com/Serilum/.issue-tracker/labels/Mod:%20Vanilla%20Zoom"
logoFile="icon.png"

[[mods]]
modId="vanillazoom"
version="2.7"
displayName="Vanilla Zoom"
displayURL="https://serilum.com/mod/vanilla-zoom"
authors="Rick South"
description='''Adds a vanilla-style zoom hotkey using the spyglass item, client-side.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Alister, Andrean Olgo, aternosorg, Cherriesaurus, Michael W. S., Nahuel Fernandez, Shana Gitnick, Tyler Behl   

If you would like to contribute too, check out https://serilum.com/donate. Appreciate it! <3   
'''

[[dependencies.vanillazoom]]
    modId="collective"
    type="required"
    versionRange="[7.78,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.vanillazoom]]
    modId="minecraft"
    type="required"
    versionRange="[1.20.6]"
    ordering="NONE"
    side="BOTH"

[[mixins]]
    config = "vanillazoom.mixins.json"